
spring.application.name=makemytrip
server.port=8080
spring.mongodb.uri=mongodb+srv://prajapatishagun2011_db_user:fubs6eB8uxBFkHYB@main.7kmdpnt.mongodb.net/?appName=main
spring.mongodb.database=makemytrip



